title: Efsane Halı Temizleme
email: adhisarlar@yahoo.com.tr
description: Halı yıkama bizim işimiz
baseurl: /efsane
url: https://halitemizleme.github.io
owner: 02324263332
email: adhisarlar@yahoo.com.tr
facebook_username: adhisarlar
address: "662/3 Sokak No:7 Buca/İZMİR"
telephone: 05300417239
copyright: Efsane Halı Temizleme
google_api_key: AIzaSyBSxRJxa3yEIGYFHZbFhqHEIxvfvoRBRHU
markdown: kramdown
