title: Efsane Halı Temizleme
email: adhisarlar@yahoo.com.tr
description: Halı temizleme bizim işimiz
baseurl: /efsane
url: https://halitemizleme.github.io
owner: İlker İspir
email: adhisarlar@yahoo.com.tr
facebook_username: adhisarlar
address: 662/3 Sokak No:7 Buca/İZMİR
telephone: 05300417239 - 02324263332
copyright: Efsane Halı Temizleme
google_api_key: AIzaSyBwnmElZuKSr63xWXcmyz1On-yHsRqEeKE
markdown: kramdown
