# Site settings
title: Efsane Halı Temizleme
email: adhisarlar@yahoo.com.tr
description: Halı yıkama bizim işimiz
baseurl: /efsane
url: https://halitemizleme.github.io

# User setting
owner: İlker İspir
email: adhisarlar@yahoo.com.tr
facebook_username: adhisarlar
address: 662/3 Sokak No:7 Buca/İZMİR
  # Feel free to add more lines here 
telephone: +905300417239
copyright: Efsane Halı Temizleme

# API settings
google_api_key: AIzaSyBSxRJxa3yEIGYFHZbFhqHEIxvfvoRBRHU

# Build settings
markdown: kramdown
