# Site settings
title: Efsane Halı Temizleme
email: adhisarlar@yahoo.com.tr
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: İlker İspir
email: adhisarlar@yahoo.com.tr
facebook_username: adhisarlar
address: 662/3 Sokak No:7 Buca/İZMİR
  - line:
  - line:
  # Feel free to add more lines here 
telephone: +905300417239
copyright: Efsane Halı Temizleme

# API settings
google_api_key:

# Build settings
markdown: kramdown
